### ISSUE TITLE
Project 5: Visualizing derby databases

### ISSUE THREAD

**Issue by tabbassidaloii** [bridgedb/nwo-hackathon-2023#5]
In the secondary to primary mapping file generated for HGNC, there are some mappings between some identifiers that shouldn't be because they are not in the input data. 

To find the issue, I would like to visualize the mapping file. @hbasaric and I tried DBeaver, but we couldn't define the correct drivers.

- I appreciate any help in visualizing derby databases.
-------

The secondary and primary scripts can be seen [here](https://github.com/tabbassidaloii/create-bridgedb-secondary2primary/).

So far the mapping file for [HGNC](https://www.genenames.org/), [UniProt](https://www.uniprot.org/), [HMDB](https://hmdb.ca/), [ChEBI](https://www.ebi.ac.uk/chebi/) and [Wikidata](https://www.wikidata.org/wiki/).

**Comment by ammar257ammar** [comment]
In order to access the Derby database and visualize the tables, the following is needed:

1- Java (17 or above)
2- Apache Derby installed (where the jar the includes the driver is)
    Installation instruction: https://db.apache.org/derby/papers/DerbyTut/install_software.html
3- an SQL client software like DBeaver or (in my test, I used squirrel "available for Linux/Windows")
    Installation: https://squirrel-sql.sourceforge.io/
4- The derby file to explore
    Connecting Squirrel to a Derby database instructions: https://db.apache.org/derby/integrate/SQuirreL_Derby.html 

**NOTE**: BridgeDB database files are compressed derby folders and the .bridge file needs to be decompressed before proceeding.

**Comment by Chris-Evelo** [comment]
Just wondering. Would it not be more elegant to have a new BridgeDb webservice call that exports the currently loaded database in a standard format like JSON or even CSV and then use existing tools to visualize and inspect the data?

**Comment by egonw** [comment]
> Would it not be more elegant to have a new BridgeDb webservice call that exports the currently loaded
> database in a standard format like JSON or even CSV and then use existing tools to visualize and inspect the data?

It's hundreds of MBs or even GBs of data in an uncompressed format. Using the webservice for this would bring it to a halt (actually, over HTTP this would likely not work in the first place).

But why would you want to do that? We know what goes in. The above need is really for debugging our own code to create Derby files.

**Comment by Chris-Evelo** [comment]
OK clear. I thought it was more to see "what is actually loaded" versus "what is in the database".

**Comment by egonw** [comment]
> OK clear. I thought it was more to see "what is actually loaded" versus "what is in the database".

Indeed. the problem is that sometimes when we request a mapping, we do not get back what we expected. So, we need to see what actually got stored in the database (and compare that to what we intended)
